Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - pollen.gemspec

AllCops:
  Exclude:
    - spec/dummy/db/schema.rb
    - vendor/**/*
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false
